elasticsearch_data:
  image: busybox
  volumes:
    - /usr/share/elasticsearch/data

elasticsearch:
  image: elasticsearch:2.1
  volumes:
    - ./elastic_config:/usr/share/elasticsearch/config
  volumes_from:
    - elasticsearch_data
  expose:
    - "9200"
    - "9300"

logstash:
  image: logstash:2.1
  links:
    - elasticsearch
  volumes:
    - ./logstash_config:/config-dir
    - /var/lib/certs/mystash/:/certs
  entrypoint: logstash -f /config-dir/logstash.conf
  ports:
    - 5698:5698

kibana:
  image: kibana:4.3
  links:
    - elasticsearch
  ports:
    - 5601:5601
  environment:
    ELASTICSEARCH_URL: 'http://elasticsearch:9200'

